add printResultsAtEnd option & update examples & test coverage
mtkennerly/kelonio pull request #4
Opened 2021-02-08 12:05 UTC by thomaschaplin

This PR includes:

- Add new `printResultsAtEnd` option which is optional (default is true)
- Add test coverage for `keepStateAtEnd`
- Add test coverage for `printResultsAtEnd`
- Update examples to have newer readme output
- Update `package-lock.json` file due to running `npm install` inside the examples folders (as various changes have been made to the main code)

2021-02-08 12:05 UTC, thomaschaplin commented
@mtkennerly I've added some further features and updated the examples, let me know what you think!

2021-02-09 02:01 UTC, mtkennerly requested changes
Thanks for the PR! Just some minor comments, but I like the new option. I can add it to the other two reporters as well before the next release.

2021-02-09 10:43 UTC, thomaschaplin commented
@mtkennerly thanks for the review, I've made the suggested changes 👍🏼

2021-02-09 22:43 UTC, mtkennerly approved these changes

2021-02-09 22:43 UTC, merged